baseURL = 'https://blog.spandanpokhrel.com.np/'
languageCode = 'en-us'
title = 'Blog | Spandan Pokhrel'
theme = 'PaperMod'

[params]
env = 'production'

defaultTheme = 'dark'
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true

[params.homeInfoParams]
Title = 'Hey, I’m Spandan'
Content = 'Security research, bug bounty, and technical writeups.'

[[menu.main]]
identifier = 'posts'
name = 'Posts'
url = '/posts/'
weight = 10

[[menu.main]]
identifier = 'tags'
name = 'Tags'
url = '/tags/'
weight = 20