baseURL = 'https://blog.spandanpokhrel.com.np/'
languageCode = 'en-us'
title = 'Blog | Spandan Pokhrel'
theme = 'PaperMod'

[params]
env = 'production'

disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true

[params.homeInfoParams]
  Title = 'Hey, I’m Spandan'
  Content = 'Security research, bug bounty, and technical writeups.'

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/spandan0x50/"

  [[params.socialIcons]]
  name = "x"
  url = "https://x.com/Spandan0x50"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/spandan0x50/"

[[menu.main]]
identifier = 'posts'
name = 'Posts'
url = '/posts/'
weight = 10

[[menu.main]]
identifier = 'tags'
name = 'Tags'
url = '/tags/'
weight = 20